"""
Weekly CEO/CFO Finance Report Generator

Queries gold_ceo_weekly_dashboard and prints a formatted text report.
Can also be wired to send via email or Slack.

Usage:
    python reporting/weekly_report.py
"""
import os
import textwrap
from datetime import date

import psycopg2


SECTIONS = {
    "cash":         "CASH POSITION",
    "ar_summary":   "ACCOUNTS RECEIVABLE (AR)",
    "ap_summary":   "ACCOUNTS PAYABLE (AP)",
    "revenue_wtd":  "REVENUE  (week to date)",
    "stripe_wtd":   "STRIPE   (week to date)",
    "recon_status": "RECONCILIATION STATUS",
}

SECTION_ORDER = list(SECTIONS.keys())


def fetch_dashboard() -> list[dict]:
    conn = psycopg2.connect(
        host=os.environ["RDS_PG_HOST"],
        port=os.environ["RDS_PG_PORT"],
        dbname=os.environ["RDS_PG_DATABASE"],
        user=os.environ["RDS_PG_USER"],
        password=os.environ["RDS_PG_PASSWORD"],
    )
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT section, metric, value, report_date
            FROM gold.gold_ceo_weekly_dashboard
            ORDER BY section, metric
        """)
        cols = [d[0] for d in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]
    finally:
        conn.close()


def render(rows: list[dict]) -> str:
    by_section: dict[str, list[dict]] = {}
    for row in rows:
        by_section.setdefault(row["section"], []).append(row)

    report_date = rows[0]["report_date"] if rows else date.today()
    width = 62

    lines = [
        "=" * width,
        "  WEEKLY FINANCE DASHBOARD".center(width),
        f"  Week of {report_date}".center(width),
        "=" * width,
    ]

    for section_key in SECTION_ORDER:
        section_rows = by_section.get(section_key, [])
        if not section_rows:
            continue
        header = SECTIONS[section_key]
        lines.append("")
        lines.append(f"  {header}")
        lines.append("  " + "-" * (width - 4))
        for r in section_rows:
            metric = r["metric"]
            value  = r["value"] if r["value"] not in (None, "None", "") else "—"
            lines.append(f"  {metric:<40} {value:>16}")

    lines.append("")
    lines.append("=" * width)
    lines.append("  Generated by xero-pipeline | Dagster + dbt + Postgres")
    lines.append("=" * width)
    return "\n".join(lines)


def main() -> None:
    rows = fetch_dashboard()
    if not rows:
        print("No dashboard data found. Has the pipeline run yet?")
        return
    print(render(rows))


if __name__ == "__main__":
    main()
